### ISSUE TITLE
BUG: Parameter --execution_provider=['gpu'] in module FaceSwapper is not in ['cpu']

### ISSUE THREAD

**Issue by alexjolig** [pozitronik/sinner#87]
**Describe the bug**
Everytime I try to choose a different execution provider, I face this error:
`LoadingException: Parameter --execution_provider=['gpu'] in module FaceSwapper is not in ['cpu']`

**To Reproduce**

python sin.py --source="cool_photo.jpg" --target="not_a_porn.mp4" --frame-processor FaceSwapper FaceEnhancer --output="result.mp4" --many-faces --execution-provider=cuda

If I choose `cuda` or `gpu` I'll face this error

Here's the full stack trace:
```
Traceback (most recent call last):
  File "projects/sinner/sin.py", line 55, in <module>
    Sin().run()
  File "projects/sinner/sin.py", line 46, in run
    BatchProcessingCore(parameters=self.parameters).run()
  File "projects/sinner/sinner/BatchProcessingCore.py", line 110, in run
    current_processor = BaseFrameProcessor.create(processor_name, self.parameters)
  File "projects/sinner/sinner/processors/frame/BaseFrameProcessor.py", line 26, in create
    return handler_class(**params)
  File "projects/sinner/sinner/processors/frame/FaceSwapper.py", line 97, in __init__
    super().__init__(parameters)
  File "projects/sinner/sinner/processors/frame/BaseFrameProcessor.py", line 49, in __init__
    super().__init__(self.parameters)
  File "projects/sinner/sinner/validators/AttributeLoader.py", line 60, in __init__
    raise LoadingException(self.errors)
sinner.validators.LoaderException.LoadingException: Parameter --execution_provider=['gpu'] in module FaceSwapper is not in ['cpu']
```

* Laptop Info:
MacBook Pro 2023 M2. 10-core GPU, 8-core CPU

**Sanity Check**
- [* ] I have the latest code from the github repository
- [* ] I have followed the installation guide

**Comment by pozitronik** [comment]
It is not an error. This message means that your current hardware/software configuration supports only the 'cpu' execution provider for onnx runtime.

**Comment by alexjolig** [comment]
@pozitronik So is there something I can do or it's just what it is?

**Comment by pozitronik** [comment]
I'll try to explain it as much, as I understand it myself.
There's ONNX Runtime, a framework that can run AI models on different types of providers; you can read [there](https://onnxruntime.ai/docs/execution-providers/) about.
You've installed the ONNX Runtime package that supports only the CpuProvider on your hardware (which utilizes the CPU, obviously). I suppose you have to find and install the `onnxruntime-silicon` package, which may support some kind of hardware acceleration.
It seems that `onnxruntime-silicon` builds can be found [there](https://github.com/cansik/onnxruntime-silicon).
I would appreciate it if you could try to check on this; I can't do it myself, as there's no Mac nearby.

**Comment by alexjolig** [comment]
@pozitronik Thanks for the explanation. I'd definitely try it and let you know how it goes.

**Comment by alexjolig** [comment]
Maybe not the right thread, but just wanted to mention that since installing `pyvirtualcam` is not supported for Mac M1/M2, the work around is to install it from source:

`pip install git+https://github.com/letmaik/pyvirtualcam`

Maybe you can add Apple silicon hints to your README file.

**Comment by pozitronik** [comment]
>Maybe you can add Apple silicon hints to your README file.

Thanks, i definitely will do that.
